export const violations = [
  { id: 'P001', desc: 'Terlambat masuk sekolah', category: 'Ringan', points: 5 },
  { id: 'P002', desc: 'Tidak memakai atribut seragam lengkap', category: 'Ringan', points: 5 },
  { id: 'P003', desc: 'Menggunakan sendal diluar waktu salat', category: 'Ringan', points: 5 },
  { id: 'P004', desc: 'Rambut tidak rapi / panjang (bagi putra)', category: 'Ringan', points: 10 },
  { id: 'P005', desc: 'Tidak mengikuti upacara bendera tanpa alasan', category: 'Ringan', points: 10 },
  { id: 'P006', desc: 'Tidak mengerjakan PR / tugas berulang kali', category: 'Ringan', points: 10 },
  { id: 'P007', desc: 'Membuang sampah sembarangan', category: 'Ringan', points: 10 },
  { id: 'P008', desc: 'Membawa makanan/minuman ke dalam kelas', category: 'Ringan', points: 10 },
  { id: 'P009', desc: 'Menggunakan MakeUp tebal', category: 'Ringan', points: 10 },
  { id: 'P010', desc: 'Tidur di kelas saat pelajaran', category: 'Ringan', points: 15 },
  { id: 'P011', desc: 'Membuat gaduh saat pelajaran', category: 'Ringan', points: 15 },
  { id: 'P012', desc: 'Membolos 1 jam pelajaran', category: 'Sedang', points: 20 },
  { id: 'P013', desc: 'Menggunakan HP saat pelajaran tanpa izin', category: 'Sedang', points: 20 },
  { id: 'P014', desc: 'Membawa barang terlarang (petasan, rokok)', category: 'Sedang', points: 25 },
  { id: 'P015', desc: 'Tidak masuk sekolah tanpa keterangan (1 hari)', category: 'Sedang', points: 25 },
  { id: 'P016', desc: 'Merusak fasilitas sekolah (ringan)', category: 'Sedang', points: 30 },
  { id: 'P017', desc: 'Berbicara kasar/kata-kata tidak sopan', category: 'Sedang', points: 30 },
  { id: 'P018', desc: 'Membawa motor tanpa helm/STNK', category: 'Sedang', points: 35 },
  { id: 'P019', desc: 'Membolos 1 hari penuh tanpa sepengetahuan orang tua', category: 'Berat', points: 40 },
  { id: 'P020', desc: 'Mencuri barang berharga di lingkungan sekolah', category: 'Berat', points: 40 },
  { id: 'P021', desc: 'Membawa / merokok di area sekolah', category: 'Berat', points: 50 },
  { id: 'P022', desc: 'Membawa / mengonsumsi minuman keras', category: 'Berat', points: 60 },
  { id: 'P023', desc: 'Berkelahi dengan teman', category: 'Berat', points: 70 },
  { id: 'P024', desc: 'Mengancam / mengintimidasi teman (bullying)', category: 'Berat', points: 80 },
  { id: 'P025', desc: 'Membawa senjata tajam tanpa izin', category: 'Berat', points: 90 },
  { id: 'P026', desc: 'Terlibat narkoba', category: 'Berat', points: 100 },
  { id: 'P027', desc: 'Melakukan tindak asusila', category: 'Berat', points: 100 },
];

export const rewards = [
  { id: 'R001', desc: 'Datang tepat waktu 1 bulan penuh', category: 'Disiplin', points: 10 },
  { id: 'R002', desc: 'Kehadiran 100% dalam 1 bulan', category: 'Disiplin', points: 15 },
  { id: 'R003', desc: 'Selalu berpakaian rapi & sesuai aturan', category: 'Sikap', points: 10 },
  { id: 'R004', desc: 'Aktif bertanya / menjawab dalam pelajaran', category: 'Sikap Belajar', points: 15 },
  { id: 'R005', desc: 'Membantu guru / teman tanpa diminta', category: 'Sikap Sosial', points: 15 },
  { id: 'R006', desc: 'Menjadi petugas upacara dengan baik', category: 'Kegiatan Sekolah', points: 20 },
  { id: 'R007', desc: 'Aktif dalam kegiatan ekstrakurikuler', category: 'Kegiatan Sekolah', points: 20 },
  { id: 'R008', desc: 'Menjadi panitia kegiatan sekolah', category: 'Organisasi', points: 25 },
  { id: 'R009', desc: 'Juara 1-3 lomba tingkat sekolah', category: 'Prestasi Akademik', points: 30 },
  { id: 'R010', desc: 'Juara 1-3 lomba tingkat kecamatan', category: 'Prestasi Akademik', points: 40 },
  { id: 'R011', desc: 'Juara 1-3 lomba tingkat kabupaten/kota', category: 'Prestasi Akademik', points: 50 },
  { id: 'R012', desc: 'Juara 1-3 lomba tingkat provinsi', category: 'Prestasi Akademik', points: 75 },
  { id: 'R013', desc: 'Juara 1-3 lomba tingkat nasional', category: 'Prestasi Akademik', points: 100 },
  { id: 'R014', desc: 'Menjadi ketua kelas/OSIS dengan tanggung jawab', category: 'Kepemimpinan', points: 30 },
  { id: 'R015', desc: 'Menjadi teladan (penghargaan khusus guru)', category: 'Sikap Teladan', points: 40 },
];
